AY2223S2-CS2113-W12-3/tp

docs/AboutUs.md
docs/team/johndoe.md
docs/team/pohwp.md

Poh Wei Pin - initial commit

---

docs/AboutUs.md

Updated Personal Details

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Inventory.java
src/main/java/seedu/duke/Item.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/Ui.java

Add initial classes and functionality

Add initial classes

---

src/main/java/seedu/duke/ColorCode.java
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Inventory.java
src/main/java/seedu/duke/Item.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/exceptions/MissingParametersException.java

Add:
- Exception classes pkg
- Color coding for aesthetic purposes
- Add functionality (Basic exception handling)
close #2 
Missing:
- Category/Tags (Not sure if needed)

feat: add functionality and color coding

---

src/main/java/seedu/duke/Inventory.java
src/main/java/seedu/duke/Trie.java
src/main/java/seedu/duke/TrieNode.java
src/test/java/seedu/duke/TrieTest.java

Add Trie Functionality

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Inventory.java
src/main/java/seedu/duke/Item.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/exceptions/EditErrorException.java
src/main/java/seedu/duke/exceptions/MissingParametersException.java
src/main/java/seedu/duke/exceptions/SearchFilterErrorException.java
src/main/java/seedu/duke/trie/Trie.java
src/main/java/seedu/duke/trie/TrieNode.java

1. Updated regex to allow spaces within add function
2. Auto-formatting for whole codebase (fix incorrect indentation and spaces)
3. Added several javadocs to some search, add and parse functions (Still have quite a few missing)

Auto-formatting & Add missing documentation

---

src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/EditCommand.java
src/main/java/seedu/duke/commands/RemoveCommand.java
src/main/java/seedu/duke/commands/SearchCommand.java
src/main/java/seedu/duke/types/Types.java
src/main/java/seedu/duke/utils/parser/Parser.java
src/test/java/seedu/duke/commands/SearchCommandTest.java

Place searchupc and search in one function in searchCommand 
Fix search using the entire name of the item
Add search tests

Add types for search

---

src/main/java/seedu/duke/commands/RemoveCommand.java
src/main/java/seedu/duke/utils/Ui.java
src/test/java/seedu/duke/commands/AddCommandTest.java

Add exception handling to RemoveCommand
Change AddCommandTest to test for every word of the item name instead of the item name

Change ITEM_NOT_FOUND to be more generic

---

src/main/java/seedu/duke/utils/Storage.java
src/main/java/seedu/duke/utils/Ui.java

Fix add item to history map not using copy constructor, causing an edge case bug

Change UI history printing method to be less overly verbose

---

src/main/java/seedu/duke/utils/Storage.java
src/test/java/seedu/duke/utils/StorageTest.java

Fix StorageTest to use addCommand.

Fix bug with history and edit/sell/restock

---

docs/UserGuide.md

Try to fix UG anchors

---

src/main/java/seedu/duke/commands/EditCommand.java
src/main/java/seedu/duke/utils/Ui.java

-Resolved some issues identified by the PE Dry Run, such as edits being made despite invalid user inputs.
-Resolved some incorrect output messages by redirecting errors to another exception.

Bug fixes for edit command.

---

src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/objects/Item.java
src/main/java/seedu/duke/utils/Ui.java
src/main/java/seedu/duke/utils/parsers/RemoveParser.java
src/test/java/seedu/duke/commands/HistoryCommandTest.java
src/test/java/seedu/duke/commands/ListCommandTest.java
src/test/java/seedu/duke/commands/SearchCommandTest.java

- Add printing of category column to list
- Update ListCommandTest accordingly
-  Standardise spelling of 'uncategorised' across UG, tests and main code
- Add line separators for alert exception handling #176

Add printing of category column to list

---

src/main/java/seedu/duke/utils/Ui.java
src/test/java/seedu/duke/commands/ListCommandTest.java

Add printing of index column to list function

---

docs/UserGuide.md

Merge conflicts caused some discrepancies, hence review the user guide again.

Further fixes to user guide

---

src/main/java/seedu/duke/utils/CommandFormat.java
src/main/java/seedu/duke/utils/Storage.java
src/main/java/seedu/duke/utils/Ui.java

Change some string literals to constants

Fix search message appearing randomly when loading the program.

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/UserGuide.md

Changed user guide to fit the format.

-Edits to the User Guide, Developer Guide

---

src/main/java/seedu/duke/utils/Storage.java

Harden session csv

---

docs/DeveloperGuide.md
src/main/java/seedu/duke/commands/FilterCommand.java

page break dg

---

docs/AboutUs.md
docs/UserGuide.md

UG QnA Section
